// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jcIDS.web.DAL;

namespace jcIDS.web.Migrations
{
    [DbContext(typeof(IDSContext))]
    [Migration("20190418020316_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("jcIDS.web.DAL.Tables.Devices", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<byte[]>("Model");

                    b.Property<DateTimeOffset>("Modified");

                    b.Property<string>("Name");

                    b.Property<string>("Token");

                    b.HasKey("ID");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("jcIDS.web.DAL.Tables.Packets", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<int>("DeviceID");

                    b.Property<DateTimeOffset>("Modified");

                    b.HasKey("ID");

                    b.ToTable("Packets");
                });
#pragma warning restore 612, 618
        }
    }
}
